# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi

cyberpi.console.println("Welcome to mBot2")

@event.is_press('up')
def is_joy_press():
    cyberpi.mesh_broadcast.set("forward")
    time.sleep(1)
    cyberpi.controller.reset_count('forward')

@event.is_press('down')
def is_joy_press1():
    cyberpi.mesh_broadcast.set("backward")
    time.sleep(1)
    cyberpi.controller.reset_count('backward')

@event.is_press('right')
def is_joy_press2():
    cyberpi.mesh_broadcast.set("right")
    time.sleep(1)
    cyberpi.controller.reset_count('right')

@event.is_press('left')
def is_joy_press3():
    cyberpi.mesh_broadcast.set("left")
    time.sleep(1)
    cyberpi.controller.reset_count('left')
    
@event.is_press('middle')
def is_joy_press4():
    cyberpi.mesh_broadcast.set("stop")

